version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html
hooks:
  BeforeInstall:
    - location: scripts/clean_html.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/reload_nginx.sh
      timeout: 300
      runas: root
